title: James Watson # your name (or website title) here
logo: "/images/IMG_1572.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>Integrated Digital Media Student at New York University<br>
  Second description 
  <br>Cognitive Bias and Machine Learning Internship<br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
